pipeline {
    agent any 

    environment {
        // L'ID que tu as confirmé dans Jenkins
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
        DOCKER_IMAGE = 'edmr/flask-app:latest'
        GITHUB_REPO = 'https://github.com/edm-r/flask_app.git'
    }

    stages {
        stage('Clonage') {
            steps {
                script {
                    echo '--- Étape 1 : Récupération du code ---'
                    git branch: 'main', url: "${GITHUB_REPO}"
                }
            }
        }
        
        stage('Image') {
            steps {
                script {
                    echo '--- Étape 2 : Construction de l\'image ---'
                    // On utilise le port 5001 comme convenu pour éviter les conflits
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }
        
        stage('Publication') {
            steps {
                script {
                    echo '--- Étape 3 : Push vers DockerHub ---'
                    // Utilisation des variables générées par Jenkins pour le login
                    sh "echo \$DOCKERHUB_CREDENTIALS_PSW | docker login -u \$DOCKERHUB_CREDENTIALS_USR --password-stdin"
                    sh "docker push $DOCKER_IMAGE"
                }
            }
        }
    }
    
    post {
        always {
            // Le bloc script ici assure que le contexte FilePath est maintenu sur ton Mac
            script {
                echo '--- Nettoyage ---'
                sh 'docker logout'
            }
        }
    }
}